version: '3.8'

services:
  slack-analyzer:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - /tmp:/tmp  # For temporary file storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s